# ============================================================
# MOSQUITTO MQTT BROKER
# ============================================================

# Écoute sur le port MQTT standard
listener 1883 0.0.0.0

# Pour la simulation PFA
allow_anonymous true

# Pas de persistance nécessaire pour la démonstration
persistence false

# Journalisation
log_type error
log_type warning
log_type notice
log_type information
